### ISSUE TITLE
exception error and issue with the server when trying to insert the data into the mortar server

### ISSUE THREAD

**Issue by reshmape** [gtfierro/mortar#11]
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
Cell In [18], line 4
      1 # load in CSV data; each row already knows it is for the 'bldg1' site
      2 # 1 CSV file per sensor, 2 days of data
      3 for datafile in glob.glob("sample-data/bldg1/*.csv"):
----> 4     c.load_csv(datafile)

File /opt/conda/lib/python3.9/site-packages/pymortar/__init__.py:98, in Client.load_csv(self, filename)
     96 resp = requests.post(url, data=b, headers={"Content-Type": "text/csv"})
     97 if not resp.ok:
---> 98     raise Exception(resp.content)

Exception: b'Error occured during transaction execution: Cannot insert readings for id 1: ERROR: insert/update/delete not permitted on chunk "_hyper_1_1_chunk" (SQLSTATE 0A000)\n'

---------------------------------------------------------------------------------------------
server issue
import requests

# register a sensor stream with relevant metadata
stream_description = {
    "SourceName": "bldg2",
    "Units": "degF",
    "Name": "mysensortest",
    "BrickURI": "http://example.com#mysensortest", # optional
    "BrickClass": "https://brickschema.org/schema/Brick#Air_Temperature_Sensor", # optional
}
requests.post(f"{URL}/register_stream?apikey={APIKEY}", json=stream_description)
<Response [500]>

**Comment by gtfierro** [comment]
You are trying to insert into a temporal range that has already been compressed by timescale. You may want to update TimescaleDB to the latest version (I believe it supports inserts into compressed chunks) or use the Timescale documentation to decompress past chunks and then insert your data. Are you trying to bulk load historical data, or just insert new data?

**Comment by reshmape** [comment]
Actually the bulk data

**Comment by reshmape** [comment]
thanks,the error got resolved for decompressing pass chunks but there is a problem with the server side for adding the data,could you please help to resolve it? 

stream_description = {
"SourceName": "bldg2",
"Units": "degF",
"Name": "mysensortest",
"BrickURI": "[http://example.com#mysensortest](http://example.com/#mysensortest)", # optional
"BrickClass": "https://brickschema.org/schema/Brick#Air_Temperature_Sensor", # optional
}
requests.post(f"{URL}/register_stream?apikey={APIKEY}", json=stream_description)
<Response [500]>

**Comment by gtfierro** [comment]
This is not enough information for me to help you debug. Can you tell me what the actual error is? Capture the response returned by `requests.post` and print out the `content` field

**Comment by reshmape** [comment]
this is response i recieved-- <Response [500]>
content--b'Cannot write to source: bldg2\n'

**Comment by gtfierro** [comment]
Make sure you read the documentation linked in the README to generate an API key for `bldg2`

**Comment by reshmape** [comment]
after following all the instructions incase of generating new api I am getting this error

**Comment by gtfierro** [comment]
I want to help you debug this, but if you are not including screenshots and stacktraces and example programs I will not be able to help you effectively. Please try and include as much information as possible in your comments so that I can use my time to debug the issue rather than ask you additional clarifying questions

**Comment by reshmape** [comment]
![imge4](https://github.com/gtfierro/mortar/assets/136608369/e70f8d12-73c6-4509-bba7-c8419292f12f)
![imge5](https://github.com/gtfierro/mortar/assets/136608369/e4b56b49-1d6d-443e-a7d4-60889f52cbe4)


i have attached the screenshots above,it will be favourable if u check,thank you

**Comment by reshmape** [comment]
![imge8](https://github.com/gtfierro/mortar/assets/136608369/54a79e0b-0c8f-4e1b-b371-7c88e73d9fad)
i am sharing the  another screenshot for your reference!

**Comment by reshmape** [comment]
thank you so much ,the issue has been resolved!

**Comment by gtfierro** [comment]
Great to hear!
